// Writes src/icons.generated.ts from lucide's icon node data — see docs/card.md#icons
import { readFileSync, writeFileSync } from "node:fs";
import { createRequire } from "node:module";
import { fileURLToPath } from "node:url";
import path from "node:path";

const require = createRequire(import.meta.url);
const here = path.dirname(fileURLToPath(import.meta.url));
const lucideVersion = require("lucide/package.json").version;

// ListApp's 26 list icons, keyed as listapp-mobile lib/list-appearance.ts keys them.
const LIST_ICONS = {
  "list-checks": "list-checks",
  star: "star",
  heart: "heart",
  sparkles: "sparkles",
  gift: "gift",
  home: "house",
  "shopping-cart": "shopping-cart",
  "shopping-bag": "shopping-bag",
  utensils: "utensils-crossed",
  coffee: "coffee",
  cake: "cake",
  plane: "plane",
  car: "car",
  "map-pin": "map-pin",
  luggage: "luggage",
  backpack: "backpack",
  briefcase: "briefcase",
  "dollar-sign": "dollar-sign",
  "book-open": "book-open",
  "graduation-cap": "graduation-cap",
  dumbbell: "dumbbell",
  music: "music",
  "party-popper": "party-popper",
  "paw-print": "paw-print",
  baby: "baby",
  wrench: "wrench",
};

const UI_ICONS = [
  "plus",
  "check",
  "ellipsis-vertical",
  "circle-check",
  "triangle-alert",
  "cloud-off",
  "grip-vertical",
  "chevron-down",
  "chevron-up",
  "arrow-up",
  "arrow-down",
  "trash",
  "x",
  "list-checks",
];

const load = async (name) => (await import(`lucide/dist/esm/icons/${name}.mjs`)).default;

const toMarkup = (nodes) =>
  nodes
    .map(([tag, attrs]) => {
      const a = Object.entries(attrs)
        .filter(([k]) => k !== "key")
        .map(([k, v]) => `${k}="${v}"`)
        .join(" ");
      return `<${tag} ${a}/>`;
    })
    .join("");

const listEntries = [];
for (const [key, lucideName] of Object.entries(LIST_ICONS)) {
  listEntries.push(`  ${JSON.stringify(key)}: ${JSON.stringify(toMarkup(await load(lucideName)))},`);
}
const uiEntries = [];
for (const name of UI_ICONS) {
  uiEntries.push(`  ${JSON.stringify(name)}: ${JSON.stringify(toMarkup(await load(name)))},`);
}

const out = `// GENERATED by scripts/gen-icons.mjs from lucide v${lucideVersion} (ISC) — do not edit.
export const LUCIDE_VERSION = ${JSON.stringify(lucideVersion)};

export const LIST_ICON_MARKUP: Record<string, string> = {
${listEntries.join("\n")}
};

export const UI_ICON_MARKUP = {
${uiEntries.join("\n")}
} as const;
`;

const target = path.resolve(here, "../src/icons.generated.ts");
let existing = "";
try {
  existing = readFileSync(target, "utf8");
} catch {
  /* first run */
}
if (existing !== out) {
  writeFileSync(target, out);
}
console.log(`icons: ${Object.keys(LIST_ICONS).length} list + ${UI_ICONS.length} ui from lucide ${lucideVersion}`);
