export const STRINGS = {
  addPlaceholder: "Add item",
  addButton: "Add item",
  active: "Active",
  completed: "Completed",
  reorder: "Reorder items",
  exitReorder: "Done reordering",
  clearCompleted: "Clear completed",
  clearConfirmTitle: "Clear completed items?",
  clearConfirmText: (n: number) =>
    `This will permanently delete ${n} completed ${n === 1 ? "item" : "items"} from the list.`,
  cancel: "Cancel",
  delete: "Delete",
  save: "Save",
  editTitle: "Edit item",
  editLabel: "Item",
  emptyTitle: "Nothing on this list",
  emptyBody: "Add the first item above, or ask Assist to add one.",
  emptyBodyNoAdd: "Ask Assist or the ListApp app to add the first item.",
  emptyBodyViewer: "Nothing has been added yet.",
  allDoneTitle: "All done",
  allDoneBody: "Every item on this list is checked off.",
  allDoneHidden: (n: number) => `${n} completed ${n === 1 ? "item is" : "items are"} hidden.`,
  authTitle: "List unavailable",
  authBody: "ListApp needs you to sign in again before this list can sync.",
  signIn: "Sign in",
  transientTitle: "Can't reach ListApp right now",
  transientBody: "Home Assistant will keep retrying. Items you see here may be stale.",
  checkIntegration: "Check integration",
  missing: (entity: string) => `Entity not found: ${entity}`,
  showMore: (n: number) => `Show ${n} more`,
  showLess: "Show less",
  markDone: (summary: string) => `Mark "${summary}" done`,
  markActive: (summary: string) => `Mark "${summary}" not done`,
  dragHandle: (summary: string) => `Move "${summary}" — drag, or use arrow keys`,
  menu: (section: string) => `${section} options`,
} as const;
